version: '3.8'

services:
  web:
    image: lappiahnuamah/devops-1:v1
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    tty: true

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot -d lawtest.auroraverusschool.org
    depends_on:
      - nginx
